/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.classLocalidad;
import main.classSeccion;
import main.methodsSQL;

/**
 *
 * @author cesar
 */
public class pLocalidad extends javax.swing.JPanel {
    private final classSeccion Seccion;
    private final classLocalidad Localidad;
    private String query;
    /**
     * Creates new form pLocalidad
     */
    public pLocalidad() {
        initComponents();
        Seccion = new classSeccion();
        Localidad = new classLocalidad();
        methodsSQL.setSeccion(Seccion);
        methodsSQL.setLocalidad(Localidad);
        mostrarSeccion();
        mostrarLocalidad();
        cargarComboBoxLocacion();
        idSec.setVisible(false);
        idLoc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSeccion = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLocalizacion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSeccion = new javax.swing.JTable();
        btnGuardarSC = new javax.swing.JButton();
        btnModificarSC = new javax.swing.JButton();
        btnEliminarSC = new javax.swing.JButton();
        btnGuardarLC = new javax.swing.JButton();
        btnModificarLC = new javax.swing.JButton();
        btnEliminarLC = new javax.swing.JButton();
        idLoc = new javax.swing.JTextField();
        idSec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbLocalizacion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 560));
        setPreferredSize(new java.awt.Dimension(730, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 37, 430));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Localizacion");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("(ejem: A1, B1, C1...)");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Localizacion ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("(ejem: Pasillo1, Pasillo2, Pasillo3...)");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));
        add(txtSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, -1));
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 150, -1));

        tbLocalizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLocalizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLocalizacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLocalizacion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 340, 210));

        tbSeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSeccionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbSeccion);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 290, 210));

        btnGuardarSC.setBackground(new java.awt.Color(0, 115, 165));
        btnGuardarSC.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnGuardarSC.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarSC.setText("Guardar");
        btnGuardarSC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardarSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSCActionPerformed(evt);
            }
        });
        add(btnGuardarSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 90, 30));

        btnModificarSC.setBackground(new java.awt.Color(0, 115, 165));
        btnModificarSC.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnModificarSC.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarSC.setText("Modificar");
        btnModificarSC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarSCActionPerformed(evt);
            }
        });
        add(btnModificarSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 90, 30));

        btnEliminarSC.setBackground(new java.awt.Color(0, 115, 165));
        btnEliminarSC.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnEliminarSC.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarSC.setText("Eliminar");
        btnEliminarSC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSCActionPerformed(evt);
            }
        });
        add(btnEliminarSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 90, 30));

        btnGuardarLC.setBackground(new java.awt.Color(0, 115, 165));
        btnGuardarLC.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnGuardarLC.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarLC.setText("Guardar");
        btnGuardarLC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardarLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLCActionPerformed(evt);
            }
        });
        add(btnGuardarLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 90, 30));

        btnModificarLC.setBackground(new java.awt.Color(0, 115, 165));
        btnModificarLC.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnModificarLC.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarLC.setText("Modificar");
        btnModificarLC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLCActionPerformed(evt);
            }
        });
        add(btnModificarLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 90, 30));

        btnEliminarLC.setBackground(new java.awt.Color(0, 115, 165));
        btnEliminarLC.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnEliminarLC.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarLC.setText("Eliminar");
        btnEliminarLC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLCActionPerformed(evt);
            }
        });
        add(btnEliminarLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 90, 30));
        add(idLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 60, -1));
        add(idSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 60, -1));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Gestion de seccion y localizacion");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 22, -1, -1));

        add(cmbLocalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, -1));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Seccion");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSCActionPerformed
        if (!camposVaciosSeccion()) {
            if (!existSeccion(txtSeccion.getText())) {
                asignarSeccion();
                if (Seccion.insert()) {
                    mostrarMensaje(2);
                } else {
                    mostrarMensaje(3);
                }
            } else {
                mostrarMensaje(1);
            }
        } else {
            mostrarMensaje(0);
        }

        limpiarCampos();
        mostrarSeccion(); 
    }//GEN-LAST:event_btnGuardarSCActionPerformed

    private void btnModificarSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarSCActionPerformed
        if (!camposVaciosSeccion()) {
            updateSeccion();
        } else {
            mostrarMensaje(3);
        }
        limpiarCampos();
        mostrarSeccion();
    }//GEN-LAST:event_btnModificarSCActionPerformed

    private void btnEliminarSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSCActionPerformed
        if (!campoVacio(idSec.getText())) {
            Seccion.setIdSeccion(Integer.parseInt(idSec.getText()));
            if (existSeccionID(Seccion.getIdSeccion())) {
                if (Seccion.delete()) {
                    mostrarMensaje(2);
                } else {
                    mostrarMensaje(3);
                }
            } else {
                mostrarMensaje(4);
            }
        } else {
            mostrarMensaje(0);
        }

        limpiarCampos();
        mostrarSeccion();
    }//GEN-LAST:event_btnEliminarSCActionPerformed

    private void btnGuardarLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLCActionPerformed
        if (!camposVaciosLocalidad()) {
            if (!existLocalidad(txtLocation.getText())) {
                asignarLocalidad();
                if (Localidad.insert()) {
                    mostrarMensaje(2);
                } else {
                    mostrarMensaje(3);
                }
            } else {
                mostrarMensaje(1);
            }
        } else {
            mostrarMensaje(0);
        }

        limpiarCampos();
        mostrarLocalidad(); 
    }//GEN-LAST:event_btnGuardarLCActionPerformed

    private void btnModificarLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLCActionPerformed
        if (!camposVaciosLocalidad()) {
            updateLocalidad();
        } else {
            mostrarMensaje(3);
        }
        limpiarCampos();
        mostrarLocalidad();
    }//GEN-LAST:event_btnModificarLCActionPerformed

    private void btnEliminarLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLCActionPerformed
        if (!campoVacio(idLoc.getText())) {
            Localidad.setIdLocalidad(Integer.parseInt(idLoc.getText()));
            if (existLocalidadID(Localidad.getIdLocalidad())) {
                if (Localidad.delete()) {
                    mostrarMensaje(2);
                } else {
                    mostrarMensaje(3);
                }
            } else {
                mostrarMensaje(4);
            }
        } else {
            mostrarMensaje(0);
        }

        limpiarCampos();
        mostrarLocalidad();
    }//GEN-LAST:event_btnEliminarLCActionPerformed

    private void tbSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSeccionMouseClicked
        try {
            int i = tbSeccion.getSelectedRow();
            query = "SELECT section, location_id from location_sections WHERE id = ?";
            ResultSet rs = methodsSQL.getExecute(query, tbSeccion.getValueAt(i, 0));
            if (rs.next()) {

                Seccion.setTxtSeccion(rs.getString(1));
                Seccion.setCmbLocacion(rs.getInt(2));
            }
            idSec.setText(tbSeccion.getValueAt(i, 0).toString());
            txtSeccion.setText(Seccion.getTxtSeccion());
            cmbLocalizacion.setSelectedIndex(Seccion.getCmbLocacion()- 1);
            
        } catch (SQLException ex) {
            Logger.getLogger(pLocalidad.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_tbSeccionMouseClicked

    private void tbLocalizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLocalizacionMouseClicked
        try {
            int i = tbLocalizacion.getSelectedRow();
            query = "SELECT location from locations WHERE id = ?";
            ResultSet rs = methodsSQL.getExecute(query, tbLocalizacion.getValueAt(i, 0));
            if (rs.next()) {

                Localidad.setTxtLocalidad(rs.getString(1));
            }
            idLoc.setText(tbLocalizacion.getValueAt(i, 0).toString());
            txtLocation.setText(Localidad.getTxtLocalidad());
            
        } catch (SQLException ex) {
            Logger.getLogger(pLocalidad.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_tbLocalizacionMouseClicked

    //Modificar valores
    public void updateLocalidad() {
        Localidad.setIdLocalidad(Integer.parseInt(idLoc.getText()));
        if (existLocalidadID(Localidad.getIdLocalidad())) {
            asignarLocalidad();
            if (Localidad.update()) {
                mostrarMensaje(2);
            } else {
                mostrarMensaje(3);
            }
        } else {
            mostrarMensaje(4);
        }
    }
    
    //Modificar valores
    public void updateSeccion() {
        Seccion.setIdSeccion(Integer.parseInt(idSec.getText()));
        if (existSeccionID(Seccion.getIdSeccion())) {
            asignarSeccion();
            if (Seccion.update()) {
                mostrarMensaje(2);
            } else {
                mostrarMensaje(3);
            }
        } else {
            mostrarMensaje(4);
        }
    }
    
    public void asignarLocalidad() {
        Localidad.setTxtLocalidad(txtLocation.getText());
    }
    
    public void asignarSeccion() {
        Seccion.setTxtSeccion(txtSeccion.getText());
        Seccion.setCmbLocacion(methodsSQL.getExecuteInt("SELECT id FROM locations WHERE location = ?", cmbLocalizacion.getSelectedItem().toString()));
    }
    
    public boolean existSeccion(String txtSeccion) {
        return methodsSQL.exists("SELECT * FROM location_sections WHERE section = ?", txtSeccion);
    }
    
    public boolean existSeccionID(Integer idSec) {
        return methodsSQL.exists("SELECT * FROM location_sections WHERE id = ?", idSec);
    }
    
    public boolean existLocalidad(String txtLocation) {
        return methodsSQL.exists("SELECT * FROM locations WHERE location = ?", txtLocation);
    }
    
    public boolean existLocalidadID(Integer idLoc) {
        return methodsSQL.exists("SELECT * FROM locations WHERE id = ?", idLoc);
    }
    
    public boolean camposVaciosLocalidad() {
        if (campoVacio(txtLocation.getText())) {
            return true;
        } else {
            return false;
        }
    }
    
    public boolean camposVaciosSeccion() {
        if (campoVacio(txtSeccion.getText()) || cmbLocalizacion.getSelectedIndex() == -1) {
            return true;
        } else {
            return false;
        }
    }
    
    //Retorna true si el campo está vacio
    public boolean campoVacio(String text) {
        text = text.replaceAll(" ", "");
        if (text.isEmpty() || text.length() == 0) {
            return true;
        } else {
            return false;
        }
    }
    
    public void mostrarSeccion() {
        query = "select s.id, s.section, l.location from location_sections s, locations l WHERE s.location_id = l.id";
        tbSeccion.setModel(methodsSQL.getTableModel(query, "ID", "Seccion", "Localidad"));
    }
    
    public void mostrarLocalidad() {
        query = "select l.id, l.location from locations l";
        tbLocalizacion.setModel(methodsSQL.getTableModel(query, "ID", "Pasillo"));
    }
    
    public void cargarComboBoxLocacion() {
        try {
            ResultSet rs = methodsSQL.getExecute("SELECT location FROM locations");
            while (rs.next()) {
                cmbLocalizacion.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(pEjemplares.class.getName()).log(Level.SEVERE, null, ex);
            

        }
        cmbLocalizacion.setSelectedIndex(-1);
    }
    
    public void limpiarCampos() {
        idSec.setText("");
        txtSeccion.setText("");
        cmbLocalizacion.setSelectedIndex(-1);
        
        idLoc.setText("");
        txtLocation.setText("");

    }
    
     //Mensajes
    public void mostrarMensaje(int value) {
        switch (value) {
            case 0:
                JOptionPane.showMessageDialog(this, "Campos vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Ese id ya exciste", "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Exito al ejecutar", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "Error al ejecutar", "Mensaje", JOptionPane.ERROR_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(this, "Ese id no existe", "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarLC;
    private javax.swing.JButton btnEliminarSC;
    private javax.swing.JButton btnGuardarLC;
    private javax.swing.JButton btnGuardarSC;
    private javax.swing.JButton btnModificarLC;
    private javax.swing.JButton btnModificarSC;
    private javax.swing.JComboBox<String> cmbLocalizacion;
    private javax.swing.JTextField idLoc;
    private javax.swing.JTextField idSec;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbLocalizacion;
    private javax.swing.JTable tbSeccion;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtSeccion;
    // End of variables declaration//GEN-END:variables
}
