/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JPanel;

/**
 *
 * @author cesar
 */
public class PrincipalPanel extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    Connection reg;

    /**
     * Creates new form PrincipalPanel
     */
    public PrincipalPanel() {
        initComponents();
        setLocationRelativeTo(null);
        pBienvenida pBv = new pBienvenida();

        pBv.setSize(750, 430);
        pBv.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pBv, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        btnEjemplares = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnMora = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnDevoluciones = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnPrestamos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnBienvenida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnCat = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLoc = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnEditoriales = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1020, 640));
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fondo.setPreferredSize(new java.awt.Dimension(900, 650));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(0, 115, 165));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEjemplares.setBackground(new java.awt.Color(0, 115, 165));
        btnEjemplares.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEjemplares.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnEjemplares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEjemplaresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEjemplaresMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEjemplaresMousePressed(evt);
            }
        });
        btnEjemplares.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ejemplares");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        btnEjemplares.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book-add-solid-24.png"))); // NOI18N
        btnEjemplares.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnEjemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 60));

        btnMora.setBackground(new java.awt.Color(0, 115, 165));
        btnMora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMora.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnMora.setPreferredSize(new java.awt.Dimension(221, 60));
        btnMora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMoraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMoraMousePressed(evt);
            }
        });
        btnMora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mora");
        btnMora.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/money-regular-24.png"))); // NOI18N
        btnMora.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnMora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 180, 60));

        btnDevoluciones.setBackground(new java.awt.Color(0, 115, 165));
        btnDevoluciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDevoluciones.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnDevoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevolucionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDevolucionesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDevolucionesMousePressed(evt);
            }
        });
        btnDevoluciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Devolucion");
        btnDevoluciones.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/package-solid-24.png"))); // NOI18N
        btnDevoluciones.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 180, 60));

        btnPrestamos.setBackground(new java.awt.Color(0, 115, 165));
        btnPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrestamos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrestamosMousePressed(evt);
            }
        });
        btnPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prestamos");
        btnPrestamos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sort-alt-2-regular-24.png"))); // NOI18N
        btnPrestamos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 180, 60));

        btnBienvenida.setBackground(new java.awt.Color(0, 115, 165));
        btnBienvenida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBienvenida.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnBienvenida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBienvenidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBienvenidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBienvenidaMousePressed(evt);
            }
        });
        btnBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bienvenida");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        btnBienvenida.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home-solid-24.png"))); // NOI18N
        btnBienvenida.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, 60));

        btnUsuario.setBackground(new java.awt.Color(0, 115, 165));
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUsuarioMousePressed(evt);
            }
        });
        btnUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Usuarios");
        btnUsuario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user-solid-24.png"))); // NOI18N
        btnUsuario.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 180, 60));

        btnCat.setBackground(new java.awt.Color(0, 115, 165));
        btnCat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCat.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCatMousePressed(evt);
            }
        });
        btnCat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Categorias y");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
        });
        btnCat.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("tipos");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
        });
        btnCat.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/category-alt-solid-24.png"))); // NOI18N
        btnCat.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 60));

        btnLoc.setBackground(new java.awt.Color(0, 115, 165));
        btnLoc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLoc.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLocMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLocMousePressed(evt);
            }
        });
        btnLoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Localidad y");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
        });
        btnLoc.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Seccion");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
        });
        btnLoc.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/file-find-solid-24.png"))); // NOI18N
        btnLoc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 180, 60));

        btnEditoriales.setBackground(new java.awt.Color(0, 115, 165));
        btnEditoriales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditoriales.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnEditoriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditorialesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditorialesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditorialesMousePressed(evt);
            }
        });
        btnEditoriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Editoriales");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });
        btnEditoriales.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencil-solid-24.png"))); // NOI18N
        btnEditoriales.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menu.add(btnEditoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 180, 60));

        fondo.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 650));

        header.setBackground(new java.awt.Color(0, 115, 165));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(72, 191, 227));
        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biblioteca amigos de Don Bosco");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        header.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 380, 5));

        fondo.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 90));
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(763, 560));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        fondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 850, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjemplaresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjemplaresMouseEntered
        if (btnEjemplares.getBackground().getRGB() == -0107165) {
            setColor(btnEjemplares);
        }
    }//GEN-LAST:event_btnEjemplaresMouseEntered

    private void btnEjemplaresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjemplaresMouseExited
        if (btnPrestamos.getBackground().getRGB() != -0107165 || btnMora.getBackground().getRGB() != -0107165
                || btnDevoluciones.getBackground().getRGB() != -0107165 || btnBienvenida.getBackground().getRGB() != -0107165
                || btnCat.getBackground().getRGB() != -0107165
                || btnLoc.getBackground().getRGB() != -0107165 || btnEditoriales.getBackground().getRGB() != -0107165) {
            resetColor(btnEjemplares);
        }
    }//GEN-LAST:event_btnEjemplaresMouseExited

    private void btnEjemplaresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjemplaresMousePressed
        setColor(btnEjemplares);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        resetColor(btnUsuario);
        resetColor(btnCat);
        resetColor(btnLoc);
                resetColor(btnEditoriales);


        // Abrir sección
        pEjemplares pAr = new pEjemplares();
        pAr.setSize(730, 560);
        pAr.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pAr, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnEjemplaresMousePressed

    private void btnPrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseEntered
        if (btnPrestamos.getBackground().getRGB() == -0107165) {
            setColor(btnPrestamos);
        }
    }//GEN-LAST:event_btnPrestamosMouseEntered

    private void btnPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseExited
        if (btnEjemplares.getBackground().getRGB() != -0107165 || btnMora.getBackground().getRGB() != -0107165
                || btnDevoluciones.getBackground().getRGB() != -0107165 || btnBienvenida.getBackground().getRGB() != -0107165
                || btnCat.getBackground().getRGB() != -0107165
                || btnLoc.getBackground().getRGB() != -0107165 || btnEditoriales.getBackground().getRGB() != -0107165) {
            resetColor(btnPrestamos);
        }
    }//GEN-LAST:event_btnPrestamosMouseExited

    private void btnPrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMousePressed
        resetColor(btnEjemplares);
        setColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        resetColor(btnUsuario);
        resetColor(btnCat);
        resetColor(btnLoc);
                resetColor(btnEditoriales);


        // Abrir sección
        pPrestamos pP = new pPrestamos();
        pP.setSize(730, 560);
        pP.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pP, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnPrestamosMousePressed

    private void btnMoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoraMouseEntered
        if (btnMora.getBackground().getRGB() == -0107165) {
            setColor(btnMora);
        }
    }//GEN-LAST:event_btnMoraMouseEntered

    private void btnMoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoraMouseExited
        if (btnEjemplares.getBackground().getRGB() != -0107165 || btnPrestamos.getBackground().getRGB() != -0107165
                || btnDevoluciones.getBackground().getRGB() != -0107165 || btnBienvenida.getBackground().getRGB() != -0107165
                || btnCat.getBackground().getRGB() != -0107165
                || btnLoc.getBackground().getRGB() != -0107165 || btnEditoriales.getBackground().getRGB() != -0107165) {
            resetColor(btnMora);
        }
    }//GEN-LAST:event_btnMoraMouseExited

    private void btnMoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoraMousePressed
        resetColor(btnEjemplares);
        resetColor(btnPrestamos);
        setColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        resetColor(btnUsuario);
        resetColor(btnCat);
        resetColor(btnLoc);
                resetColor(btnEditoriales);


        // Abrir sección
        pMora pM = new pMora();
        pM.setSize(730, 560);
        pM.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pM, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnMoraMousePressed

    private void btnDevolucionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolucionesMouseEntered
        if (btnDevoluciones.getBackground().getRGB() == -0107165) {
            setColor(btnDevoluciones);
        }
    }//GEN-LAST:event_btnDevolucionesMouseEntered

    private void btnDevolucionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolucionesMouseExited
        if (btnEjemplares.getBackground().getRGB() != -0107165 || btnPrestamos.getBackground().getRGB() != -0107165
                || btnMora.getBackground().getRGB() != -0107165 || btnBienvenida.getBackground().getRGB() != -0107165
                || btnCat.getBackground().getRGB() != -0107165
                || btnLoc.getBackground().getRGB() != -0107165 || btnEditoriales.getBackground().getRGB() != -0107165) {
            resetColor(btnDevoluciones);
        }
    }//GEN-LAST:event_btnDevolucionesMouseExited

    private void btnDevolucionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolucionesMousePressed
        resetColor(btnEjemplares);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        setColor(btnDevoluciones);
        resetColor(btnBienvenida);
        resetColor(btnUsuario);
        resetColor(btnCat);
        resetColor(btnLoc);
                resetColor(btnEditoriales);


        // Abrir sección
        pDevoluciones pD = new pDevoluciones();
        pD.setSize(730, 560);
        pD.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pD, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnDevolucionesMousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void btnBienvenidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBienvenidaMouseEntered
        if (btnBienvenida.getBackground().getRGB() == -0107165) {
            setColor(btnBienvenida);
        }
    }//GEN-LAST:event_btnBienvenidaMouseEntered

    private void btnBienvenidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBienvenidaMouseExited
        if (btnEjemplares.getBackground().getRGB() != -0107165 || btnPrestamos.getBackground().getRGB() != -0107165
                || btnMora.getBackground().getRGB() != -0107165 || btnDevoluciones.getBackground().getRGB() != -0107165
                || btnCat.getBackground().getRGB() != -0107165
                || btnLoc.getBackground().getRGB() != -0107165 || btnEditoriales.getBackground().getRGB() != -0107165) {
            resetColor(btnBienvenida);
        }
    }//GEN-LAST:event_btnBienvenidaMouseExited

    private void btnBienvenidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBienvenidaMousePressed
        resetColor(btnEjemplares);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        setColor(btnBienvenida);
        resetColor(btnUsuario);
        resetColor(btnCat);
        resetColor(btnLoc);
                resetColor(btnEditoriales);


        // Abrir sección
        pBienvenida pB = new pBienvenida();
        pB.setSize(730, 560);
        pB.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pB, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnBienvenidaMousePressed

    private void btnUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseEntered
        if (btnUsuario.getBackground().getRGB() == -0107165) {
            setColor(btnUsuario);
        }
    }//GEN-LAST:event_btnUsuarioMouseEntered

    private void btnUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseExited
        if (btnEjemplares.getBackground().getRGB() != -0107165 || btnPrestamos.getBackground().getRGB() != -0107165
                || btnMora.getBackground().getRGB() != -0107165 || btnDevoluciones.getBackground().getRGB() != -0107165
                || btnBienvenida.getBackground().getRGB() != -0107165 || btnCat.getBackground().getRGB() != -0107165
                || btnLoc.getBackground().getRGB() != -0107165 || btnEditoriales.getBackground().getRGB() != -0107165) {
            resetColor(btnUsuario);
        }
    }//GEN-LAST:event_btnUsuarioMouseExited

    private void btnUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMousePressed
        resetColor(btnEjemplares);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        setColor(btnUsuario);
        resetColor(btnCat);
        resetColor(btnLoc);
                resetColor(btnEditoriales);


        // Abrir sección
        pUsuario pU = new pUsuario();
        pU.setSize(730, 560);
        pU.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pU, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnUsuarioMousePressed

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void btnCatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatMouseEntered
        if (btnCat.getBackground().getRGB() == -0107165) {
            setColor(btnCat);
        }
    }//GEN-LAST:event_btnCatMouseEntered

    private void btnCatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatMouseExited
        if (btnEjemplares.getBackground().getRGB() != -0107165 || btnPrestamos.getBackground().getRGB() != -0107165
                || btnMora.getBackground().getRGB() != -0107165 || btnDevoluciones.getBackground().getRGB() != -0107165
                || btnBienvenida.getBackground().getRGB() != -0107165 || btnUsuario.getBackground().getRGB() != -0107165
                || btnLoc.getBackground().getRGB() != -0107165 || btnEditoriales.getBackground().getRGB() != -0107165) {
            resetColor(btnCat);
        }
    }//GEN-LAST:event_btnCatMouseExited

    private void btnCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatMousePressed
        resetColor(btnEjemplares);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        resetColor(btnUsuario);
        setColor(btnCat);
        resetColor(btnLoc);
                resetColor(btnEditoriales);


        // Abrir sección
        pCategoriaTipos pCT = new pCategoriaTipos();
        pCT.setSize(730, 560);
        pCT.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pCT, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnCatMousePressed

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseEntered

    private void btnLocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocMouseEntered
         if (btnLoc.getBackground().getRGB() == -0107165) {
            setColor(btnLoc);
        }
    }//GEN-LAST:event_btnLocMouseEntered

    private void btnLocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocMouseExited
            if (btnEjemplares.getBackground().getRGB() != -0107165 || btnPrestamos.getBackground().getRGB() != -0107165
                || btnMora.getBackground().getRGB() != -0107165 || btnDevoluciones.getBackground().getRGB() != -0107165
                || btnBienvenida.getBackground().getRGB() != -0107165 || btnUsuario.getBackground().getRGB() != -0107165
                || btnCat.getBackground().getRGB() != -0107165 || btnEditoriales.getBackground().getRGB() != -0107165) {
            resetColor(btnLoc);
        }
    }//GEN-LAST:event_btnLocMouseExited

    private void btnLocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocMousePressed
         resetColor(btnEjemplares);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        resetColor(btnUsuario);
        resetColor(btnCat);
        setColor(btnLoc);
                resetColor(btnEditoriales);


        // Abrir sección
        pLocalidad pL = new pLocalidad();
        pL.setSize(730, 560);
        pL.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pL, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnLocMousePressed

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void btnEditorialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialesMouseEntered
         if (btnEditoriales.getBackground().getRGB() == -0107165) {
            setColor(btnEditoriales);
        }
    }//GEN-LAST:event_btnEditorialesMouseEntered

    private void btnEditorialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialesMouseExited
          if (btnEjemplares.getBackground().getRGB() != -0107165 || btnPrestamos.getBackground().getRGB() != -0107165
                || btnMora.getBackground().getRGB() != -0107165 || btnDevoluciones.getBackground().getRGB() != -0107165
                || btnBienvenida.getBackground().getRGB() != -0107165 || btnUsuario.getBackground().getRGB() != -0107165
                || btnCat.getBackground().getRGB() != -0107165 || btnLoc.getBackground().getRGB() != -0107165) {
            resetColor(btnEditoriales);
        }
    }//GEN-LAST:event_btnEditorialesMouseExited

    private void btnEditorialesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialesMousePressed
         resetColor(btnEjemplares);
        resetColor(btnPrestamos);
        resetColor(btnMora);
        resetColor(btnDevoluciones);
        resetColor(btnBienvenida);
        resetColor(btnUsuario);
        resetColor(btnCat);
        resetColor(btnLoc);
        setColor(btnEditoriales);

        // Abrir sección
        pEditoriales pE = new pEditoriales();
        pE.setSize(730, 560);
        pE.setLocation(0, 0);

        contenedor.removeAll();
        contenedor.add(pE, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnEditorialesMousePressed

    /**
     * @param args the command line arguments
     */
    void setColor(JPanel panel) {
        panel.setBackground(new Color(0, 107, 165));
    }

   
    void resetColor(JPanel panel){
        panel.setBackground(new Color(0,115,165));
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBienvenida;
    private javax.swing.JPanel btnCat;
    private javax.swing.JPanel btnDevoluciones;
    private javax.swing.JPanel btnEditoriales;
    private javax.swing.JPanel btnEjemplares;
    private javax.swing.JPanel btnLoc;
    private javax.swing.JPanel btnMora;
    private javax.swing.JPanel btnPrestamos;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
