/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.classUsuarios;
import main.methodsSQL;

/**
 *
 * @author cesar
 */
public class pUsuario extends javax.swing.JPanel {
    private final classUsuarios Usuario;
    private String query;
    /**
     * Creates new form pUsuario
     */
    public pUsuario() {
        initComponents();
        Usuario = new classUsuarios();
        methodsSQL.setUsuarios(Usuario);
        cargarComboBoxRole();
        mostrarUser();
        idUser.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboRol = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        btnGuardarU = new javax.swing.JButton();
        btnModificarU = new javax.swing.JButton();
        btnEliminarU = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        idUser = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Gestion de usuarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 22, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Ingrese nombre completo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 201, -1));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Ingrese correo electronico");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 201, -1));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ingrese contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 201, -1));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Ingrese Rol ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        add(comboRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 201, -1));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ingrese su Carnet");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        add(txtCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 201, -1));

        btnGuardarU.setBackground(new java.awt.Color(0, 115, 165));
        btnGuardarU.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnGuardarU.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarU.setText("Guardar");
        btnGuardarU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUActionPerformed(evt);
            }
        });
        add(btnGuardarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 90, 30));

        btnModificarU.setBackground(new java.awt.Color(0, 115, 165));
        btnModificarU.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnModificarU.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarU.setText("Modificar");
        btnModificarU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUActionPerformed(evt);
            }
        });
        add(btnModificarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 90, 30));

        btnEliminarU.setBackground(new java.awt.Color(0, 115, 165));
        btnEliminarU.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnEliminarU.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarU.setText("Eliminar");
        btnEliminarU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUActionPerformed(evt);
            }
        });
        add(btnEliminarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 90, 30));

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbUsers);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 630, 220));
        add(idUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 60, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUActionPerformed
        if (!camposVaciosUser()) {
            if (!existUser(txtCarnet.getText())) {
                asignarUSer();
                if (Usuario.insert()) {
                    mostrarMensaje(2);
                } else {
                    mostrarMensaje(3);
                }
            } else {
                mostrarMensaje(1);
            }
        } else {
            mostrarMensaje(0);
        }

        limpiarCampos();
        mostrarUser(); 
    }//GEN-LAST:event_btnGuardarUActionPerformed

    private void btnModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUActionPerformed
        if (!camposVaciosUser()) {
            updateUser();
        } else {
            mostrarMensaje(3);
        }
        limpiarCampos();
        mostrarUser();
    }//GEN-LAST:event_btnModificarUActionPerformed

    private void btnEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUActionPerformed
        if (!campoVacio(idUser.getText())) {
            Usuario.setIdUsuario(Integer.parseInt(idUser.getText()));
            if (existUserID(Usuario.getIdUsuario())) {
                if (Usuario.delete()) {
                    mostrarMensaje(2);
                } else {
                    mostrarMensaje(3);
                }
            } else {
                mostrarMensaje(4);
            }
        } else {
            mostrarMensaje(0);
        }

        limpiarCampos();
        mostrarUser();
    }//GEN-LAST:event_btnEliminarUActionPerformed

    private void tbUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsersMouseClicked
        try {
            int i = tbUsers.getSelectedRow();
            query = "SELECT email, identification, full_name, user_role FROM users WHERE id = ?";
            ResultSet rs = methodsSQL.getExecute(query, tbUsers.getValueAt(i, 0));
            if (rs.next()) {

                Usuario.setTxtEmail(rs.getString(1));
                Usuario.setTxtIdentificacion(rs.getString(2));
                Usuario.setTxtNombreCompleto(rs.getString(3));
                Usuario.setCmbRole(rs.getInt(4));
            }
            idUser.setText(tbUsers.getValueAt(i, 0).toString());
            txtFullName.setText(Usuario.getTxtNombreCompleto());
            txtEmail.setText(Usuario.getTxtEmail());
            txtCarnet.setText(Usuario.getTxtIdentificacion());
            comboRol.setSelectedIndex(Usuario.getCmbRole()- 1);
            
        } catch (SQLException ex) {
            Logger.getLogger(pUsuario.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_tbUsersMouseClicked

    public void updateUser() {
        Usuario.setIdUsuario(Integer.parseInt(idUser.getText()));
        if (existUserID(Usuario.getIdUsuario())) {
            asignarUSer();
            if (Usuario.update()) {
                mostrarMensaje(2);
            } else {
                mostrarMensaje(3);
            }
        } else {
            mostrarMensaje(4);
        }
    }
    
    public void asignarUSer() {
        Usuario.setTxtNombreCompleto(txtFullName.getText());
        Usuario.setTxtEmail(txtEmail.getText());
        Usuario.setTxtIdentificacion(txtCarnet.getText());
        Usuario.setTxtContra(txtPassword.getText());
        Usuario.setCmbRole(methodsSQL.getExecuteInt("SELECT id FROM user_roles WHERE name = ?", comboRol.getSelectedItem().toString()));
    }
    
    public boolean existUser(String txtCarnet) {
        return methodsSQL.exists("SELECT * FROM users WHERE identification = ?", txtCarnet);
    }
    
    public boolean existUserID(Integer idUser) {
        return methodsSQL.exists("SELECT * FROM users WHERE id = ?", idUser);
    }
    
     public boolean camposVaciosUser() {
        if (campoVacio(txtFullName.getText()) || campoVacio(txtEmail.getText()) || campoVacio(txtCarnet.getText()) 
                || campoVacio(txtCarnet.getText()) || comboRol.getSelectedIndex() == -1) {
            return true;
        } else {
            return false;
        }
    }
     
    //Retorna true si el campo está vacio
    public boolean campoVacio(String text) {
        text = text.replaceAll(" ", "");
        if (text.isEmpty() || text.length() == 0) {
            return true;
        } else {
            return false;
        }
    }
    
    public void mostrarUser() {
        query = "SELECT u.id, u.email, u.identification, u.full_name, r.name FROM users u, user_roles r WHERE u.user_role = r.id";
        tbUsers.setModel(methodsSQL.getTableModel(query, "ID", "Correo", "Carnet", "Nombre completo", "Rol de Usuario"));
    }
    
    public void cargarComboBoxRole() {
        try {
            ResultSet rs = methodsSQL.getExecute("SELECT name FROM user_roles");
            while (rs.next()) {
                comboRol.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(pEjemplares.class.getName()).log(Level.SEVERE, null, ex);
            

        }
        comboRol.setSelectedIndex(-1);
    }
    
    public void limpiarCampos() {
        txtFullName.setText("");
        txtEmail.setText("");
        txtCarnet.setText("");
        txtPassword.setText("");
        comboRol.setSelectedIndex(-1);
    }
    
    //Mensajes
    public void mostrarMensaje(int value) {
        switch (value) {
            case 0:
                JOptionPane.showMessageDialog(this, "Campos vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Ese id ya exciste", "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Exito al ejecutar", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "Error al ejecutar", "Mensaje", JOptionPane.ERROR_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(this, "Ese id no existe", "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarU;
    private javax.swing.JButton btnGuardarU;
    private javax.swing.JButton btnModificarU;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JTextField idUser;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbUsers;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
